### ISSUE TITLE
 VariantType::SetVariant(const VariantType& var) produces a memory leak.

### ISSUE THREAD

**Issue by reven86** [dava/dava.engine#286]
The line [437](https://github.com/dava/dava.engine/blob/development/Sources/Internal/FileSystem/VariantType.cpp#L437) which sets **type** to TYPE_NONE prevents the further deallocation of any pointer held by VariantType. The ReleasePointer method relies on **type** member when doing deallocation which is now set to TYPE_NONE.

Example (pseudo-code):

```
VariantType a, b;
a.SetString(String("test"));
b.SetInt32(111);
a.SetVariant(b);   // memory allocated to hold "test" string is not freed
```

**Comment by dizzerr** [comment]
Branch with the fix is already in testing. Thanks.

**Comment by klesch** [comment]
Fixed
