### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by NTanker123** [dava/dava.engine#287]
I want to run this for World of Tanks Blitz, but I don't know how to run this.

**Comment by sergeyreznik** [comment]
@NTanker123 what kind of issues are you experiencing? I don't have any troubles running *this* for WoT Blitz

**Comment by NTanker123** [comment]
Well, I don't know how to run DAVAFramework.
There is no .exe to run the program.

I want to learn this engine for program and coding learning. (Sorry my bad English)

**Comment by sergeyreznik** [comment]
@NTanker123 You have to compile everything from source. You will be need CMake and Qt to generate and compile projects. I will ask somebody to make detailed building instructions.

**Comment by NTanker123** [comment]
Thank you very much!

**Comment by AlekseiKanash** [comment]
Heh. Even if you build the engine - it is almost useless without a lot of documentation.

**Comment by NTanker123** [comment]
@sergeyreznik it's 3/25 now and still no building instruction..

**Comment by subdiox** [comment]
https://github.com/dava/dava.engine/blob/development/Docs/ResourceEditorPublic.md

You should check "Docs" directory, which usually contains documentation.

**Comment by klesch** [comment]
We uploaded instruction mentioned by @subdiox
