### ISSUE TITLE
Обновление 4.7

### ISSUE THREAD

**Issue by XashLife** [dava/dava.engine#291]
Ребят, не расскажите как можно было убить производительность ничего глобального не добавив в обновлении? За место вечного 61 кадра мы получаем 40-60 не зависимо от настроек графики. Steam версия игры, клиенту выделены 2 отдельных ядра

**Comment by venusdoom** [comment]
@XashLife , привет! 
Опиши, пожалуйста:
- окружение, на котором тестировался клиент игры (конфигурацию ПК, dxdiag например),
- не изменялись ли конфигурация/ПО/драйверы в последнее время (когда стал замечать проблемы),
- работают ли какие-нибудь приложения в фоне, при запущенном клиенте игры (информация от диспетчера задач),
- что будет, если запускать клиент игры по умолчанию, без ручного выделения/распределения мощностей системы (фраза про выделены 2 ядра)?

**Comment by XashLife** [comment]
1) ASRock QC5000M-ITX/PH
2) Нет, ничего не менялось. разница в производительности имеется исключительно между обновлениями
3) Да, оперативной памяти более чем достаточно для работы фоновых приложений, а для игры используются отдельные ядра
4) Первые 2 ядра заняты фоновыми процессами
