### ISSUE TITLE
DebugDrawSystem duplicated in repository

### ISSUE THREAD

**Issue by dreamora** [dava/dava.engine#293]
Platform:
- OSX 10.13
- XCode 9.2

- Python 2.7.10 default at path (2.7.14 and 3.6 also installed in /usr/local/bin)

File in question:
Modules/REPlatform/Sources/REPlatform/Scene/Private/Systems/DebugDrawSystem.cpp

When attempting to compile the current version on branch development following the CMake instructions in Docs/ResourceEditorPublic.md, the compilation fails with ResourceEditor::eSceneObjectType not found
This is caused by 

- void DebugDrawSystem::SetRequestedObjectType(ResourceEditor::eSceneObjectType _objectType)
- ResourceEditor::eSceneObjectType DebugDrawSystem::GetRequestedObjectType() const

because ResourceEditor::eSceneObjectType does not exist in the repository.

I would suspect that it under normal circumstances should be found in
Modules/REPlatform/Sources/REPlatform/Global/constant.h as all other ResourceEditor enums are defined there, but the constant.h is not included in DebugDrawSystem either so the access to ResourceEditor::e in general appears to violated the otherwise used code practices?

I did some experiments resolving the first set of problems and it seems that even when resolving the above problem, more and more non compilable things appear in DebugDrawSystem.cpp. Is this class meant to be in the public repository and if so is it up to date and synced with a potential private version.

Additional: I just realized that there are two DebugDrawSystem.cpp in the build directory generated by CMake:
- Modules/REPlatform/Sources/REPlatform/Scene/Private/Systems/DebugDrawSystem.cpp
- Modules/REPlatform/Sources/REPlatform/Scene/Private/Systems/DebugDrawSystem/DebugDrawSystem.cpp

after deleting the first one, the compile issues related to DebugDrawSystem.cpp can be resolved.

**Comment by klesch** [comment]
Thanks. We will fixed our push-to-github script to fix this problem.
Modules/REPlatform/Sources/REPlatform/Scene/Private/Systems/DebugDrawSystem.cpp - is wrong file

**Comment by klesch** [comment]
Try one more time. We updated out upload script and re-uploaded sources
