### ISSUE TITLE
Duplicate DVApplication.h on OSX

### ISSUE THREAD

**Issue by dreamora** [dava/dava.engine#294]
Platform:
- OSX 10.13
- XCode 9.2
- Python 2.7.10 default at path (2.7.14 and 3.6 also installed in /usr/local/bin)

The repository currently contains DVApplication.h twice for OSX:
- Engine/Private/OsX/DVApplication.h
- Engine/Private/Mac/DVApplication.h

This breaks compilation on OSX.
Based on what I see I assume that the directory OsX is meant to be removed as it is empty aside of DVApplication unlike the Mac directory.

**Comment by klesch** [comment]
It's the same problem with our script. Will be fixed soon

**Comment by klesch** [comment]
Try one more time. We updated out upload script and re-uploaded sources
