### ISSUE TITLE
Incorrect char* to uint* cast in UIRichAliasMap::PutAliasFromXml

### ISSUE THREAD

**Issue by dreamora** [dava/dava.engine#296]
System:
- OSX 10.13
- OSX 9.2

File: UIRichAliasMap
Function: UIRichAliasMap::PutAliasFromXml
Line: 69

UIRichAliasMap attempts to cast the provided string to int8* and then to uint8*.
The called function XMLParser::ParseBytesEx though is defined as
XMLParserStatus XMLParser::ParseBytesEx(const char8* bytes, int32 length, XMLParserDelegate* delegateptr)

The expected const char8* bytes is not compatible with const uint8, creating a compile errors of ResourceEditor on OSX.

**Comment by dirondin** [comment]
Thanks for issue. 
We have some problems with our push-to-github script and we will repare it.
This file is old and should be removed.

**Comment by klesch** [comment]
Try one more time. We updated out upload script and re-uploaded sources
