### ISSUE TITLE
Binaries in the repo, bandwidth issue.

### ISSUE THREAD

**Issue by exhu** [dava/dava.engine#48]
Why are a lot of libs in the binary form in the repository? It's become really huge. 

All third-party libs must be easy to build with instructions. If nobody can build it easily then the person who has committed those libs must provide instructions to replicate!

Resource packer etc. tools are ok to be binary, but consider hosting them at google code downloads etc.

The repo is at 2 GB now, takes forever to do git clone.

**Comment by binaryzebra** [comment]
Working on this. Hopefully soon we'll have scripts for building everything including third party libs.

**Comment by klesch** [comment]
Now we store binaries at LFS. Issue isn't actual
