### ISSUE TITLE
Format doesn't work in iOS, macosx

### ISSUE THREAD

**Issue by exhu** [dava/dava.engine#80]
No unicode is supported in wchar_t functions like printf, vswprintf etc. on iOS, macosx.
http://stackoverflow.com/questions/11713745/why-does-the-printf-family-of-functions-care-about-locale

So DAVA::Format(char16 *...) is not usable.

**Comment by binaryzebra** [comment]
Is it still a problem?

**Comment by klesch** [comment]
Issue isn't actual
