### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [dava/dava.engine#82]
I would like to point out that identifiers like "[```__DAVAENGINE_H__```](https://github.com/dava/dava.framework/blob/ffad06a9e9e4761e9a5964d9b615d2a107539a15/Sources/Internal/DAVAEngine.h#L30)" and "[```__DAVAENGINE_BASEOBJECT_H__```](https://github.com/dava/dava.framework/blob/cd44fbb3c7d49fa81c6a4d43ffede33747a60aeb/Sources/Internal/Base/BaseObject.h#L30)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPPDonotdeclareordefineareservedidentifier-NoncompliantCodeExampleHeaderGuard "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by binaryzebra** [comment]
We do not plan to change that.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?
